# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x12\x07gateway\x1a\x1cgoogle/protobuf/struct.proto\"\xd3\x02\n\x14InvokeServiceRequest\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x14\n\x0cservice_slug\x18\x03 \x01(\t\x12\x14\n\x0cservice_type\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x16\n\x0e\x65xecution_mode\x18\x06 \x01(\t\x12.\n\rinput_payload\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x16\n\ttimeout_s\x18\x08 \x01(\x05H\x00\x88\x01\x01\x12\x1d\n\x10\x63onsumer_site_id\x18\t \x01(\tH\x01\x88\x01\x01\x12\x1d\n\x10provider_site_id\x18\n \x01(\tH\x02\x88\x01\x01\x42\x0c\n\n_timeout_sB\x13\n\x11_consumer_site_idB\x13\n\x11_provider_site_id\"R\n\x15InvokeServiceResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\njob_status\x18\x02 \x01(\t\x12\x15\n\rinvocation_id\x18\x03 \x01(\t2`\n\x0eGatewayService\x12N\n\rInvokeService\x12\x1d.gateway.InvokeServiceRequest\x1a\x1e.gateway.InvokeServiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOKESERVICEREQUEST']._serialized_start=57
  _globals['_INVOKESERVICEREQUEST']._serialized_end=396
  _globals['_INVOKESERVICERESPONSE']._serialized_start=398
  _globals['_INVOKESERVICERESPONSE']._serialized_end=480
  _globals['_GATEWAYSERVICE']._serialized_start=482
  _globals['_GATEWAYSERVICE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
